spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:rest_orders}?serverTimezone=CST&useLegacyDatetimeCode=false
    username: ${MYSQL_USER:joe}
    password: ${MYSQL_PASS:Ast0n762616@nD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect


#validate: validate the schema, makes no change to the database (PRODUCTION)
#update: update the schema
#create: create the schema, destroy the existing schema.
#create-drop: drop the schema at the end.