server:
  port: 0
spring:
  application:
    name: ORDER-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
employeeUrl: http://EMPLOYEE-SERVICE
