spring:
  application:
    name: KAFKA-CONSUMER
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
