eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  application:
    name: "eureka"
  cloud:
    config:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

